Repository FHIDev/Fhi.VersionApi, pull requests merged in 2025-04, with the labels that each got.

#10 Changed Service connection name for publish
  .gitignore
  VersionApi.Azure.Publish.yaml
  gitversion.yml
Labels: bug, is:build

#9 Fixed folder (test vs Test)
  Fhi.VersionApi.Test/CodeVersionTagTest.cs
  Fhi.VersionApi.Test/Fhi.VersionApi.Test.csproj
  Fhi.VersionApi.Test/GlobalUsings.cs
  Fhi.VersionApi.Test/VersionApiControllerTest.cs
  gitversion.yml
Labels: internal, blocked

#8 Changed typo in environment
  .gitignore
  Fhi.VersionApi/Controllers/VersionApiControllers.cs
  Fhi.VersionApi/VersionDTO.cs
Labels: bug

#11 Deleted duplicated project
  VersionApi.test/Fhi.VersionApi.Test.csproj
Labels: internal

#12 Update nuget packages
  Fhi.VersionApi.Test/Fhi.VersionApi.Test.csproj
  Fhi.VersionApi/Fhi.VersionApi.csproj
Labels: dependencies

#14 Update WrapThat.Version from 1.3.0 to 1.4.2
  Fhi.VersionApi/Fhi.VersionApi.csproj
Labels: dependencies

#15 Deploy should only trigger for main
  VersionApi.Azure.Publish.yaml
Labels: internal, is:build
